### ISSUE TITLE
Selenium 3.14.0 not working with -enablePassThrough

### ISSUE THREAD

**Issue by patrickbussmann** [dhoer/choco-selenium#31]
```
C:\tools\selenium>java  -jar "C:\tools\selenium\selenium-server-standalone.jar" -enablePassThrough True -role standalone -port 4444 -browserTimeout 0 -timeout 1800
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '-enablePassThrough' but no main parameter was defined in your arg class
        at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:936)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:752)
        at com.beust.jcommander.JCommander.parse(JCommander.java:340)
        at com.beust.jcommander.JCommander.parse(JCommander.java:319)
        at org.openqa.grid.internal.cli.StandaloneCliOptions.parse(StandaloneCliOptions.java:28)
        at org.openqa.grid.selenium.GridLauncherV3$1.<init>(GridLauncherV3.java:256)
        at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$0(GridLauncherV3.java:255)
        at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:163)
        at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:97)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:81)
```

When I remove `-enablePassThrough True` from `C:\tools\selenium\standalone.cmd` then it's working successfully.

```
C:\tools\selenium>java  -jar "C:\tools\selenium\selenium-server-standalone.jar" -role standalone -port 4444 -browserTimeout 0 -timeout 1800
14:23:34.328 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.14.0', revision: 'aacccce0'
14:23:34.329 INFO [GridLauncherV3$1.launch] - Launching a standalone Selenium Server on port 4444
2018-09-21 14:23:34.449:INFO::main: Logging initialized @452ms to org.seleniumhq.jetty9.util.log.StdErrLog
14:23:34.754 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
```

**Comment by yukisato** [comment]
According to https://github.com/SeleniumHQ/selenium/issues/5385#issuecomment-360725415, `-enablePassThrough` option has already been removed in version 3.9.
>@barancev
>This option will be completely removed in version 3.9
>Please log issues if something is not working as expected without this option.
